config_dict = {
    "batch_size": 128,
    "epochs": 30,
    "pretrain_epochs": 50,
    "heuristic_lr": 0.1,
    "heuristic_epochs": 30,
    "heuristic_threshold": 1e-2,
    "itr_lr": 0.1,
    "initial_prune_rate": 0.1,
    "one_time_prune_rate": 0.2,
    "filter_prune_rate": 0.25,
    "itr_epochs": 30,
    "ft_lr": 1e-2,
    "pr_lr": 1e-2,
    "pretrain_lr": 1e-1,
    "pretrained_unstructured_file": "./pretrained_resnet18.pth",
    "pretrained_structured_file": "./pretrained_resnet18_structured.pth",
    "ft_label": 0,
    "pr_label": 1,
    "bias_key": 'bias',
    "weight_key": 'weight',
    "activate_key": 'activate_flag'
}